create schema OLIST;
CREATE TABLE IF NOT EXISTS 
	OLIST.audit_log
(
	event_time TIMESTAMP default current_timestamp,
	RUN_ID VARCHAR(20),
	EVENT_TYPE VARCHAR(50),
	STATUS VARCHAR(20),
	RESP_MESSAGE VARCHAR(100),
	AUDIT_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);  -- for all audits


-- Main tables
CREATE TABLE OLIST.payment_facts (
    order_id VARCHAR NOT NULL,
    payment_sequential BIGINT NOT NULL,
    payment_installments INTEGER,
    payment_type VARCHAR,
    payment_value FLOAT,
    proc_run_id VARCHAR,
    source_payment_file VARCHAR,
    created_on TIMESTAMP,
    updated_on TIMESTAMP,
    PRIMARY KEY (order_id, payment_sequential)
);

CREATE TABLE OLIST.order_summary (
    order_id VARCHAR PRIMARY KEY,
    customer_id VARCHAR,
    order_status VARCHAR,
    order_approved_at TIMESTAMP,
    order_purchase_timestamp TIMESTAMP,
    order_delivered_carrier_date TIMESTAMP,
    order_delivered_customer_date TIMESTAMP,
    order_estimated_delivery_date TIMESTAMP,
    no_of_payments BIGINT,
    payment_installments INTEGER,
    payment_types_used VARCHAR,
    total_payment_value FLOAT,
    created_by_proc_run_id VARCHAR,
    updated_by_proc_run_id VARCHAR,
    source_order_file VARCHAR,
    source_payment_file VARCHAR,
    created_on TIMESTAMP,
    updated_on TIMESTAMP
);

-- Staging tables (same structure)
CREATE TABLE OLIST.payment_facts_staging (LIKE payment_facts);
CREATE TABLE OLIST.order_summary_staging (LIKE order_summary);

-- Sync tracking table
CREATE TABLE OLIST.sync_tracking (
    table_name VARCHAR PRIMARY KEY,
    last_version BIGINT,
    last_sync_time TIMESTAMP,
    run_id VARCHAR
);